# Generated by Django 4.2 on 2023-04-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_movieorder_movie_orders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieorder",
            name="buyed_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
